version: '3.8'

services:
  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: pricyla_store
      MYSQL_USER: pricyla_user
      MYSQL_PASSWORD: password
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

  backend:
    build: ./back-end
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_USER: pricyla_user
      DB_PASSWORD: password
      DB_NAME: pricyla_store
      DB_PORT: 3306
  
  frontend:
    build: ./front-end
    ports: 
      - "3000:3000"
    depends_on:
      - backend
    
volumes:
  db_data: